package gleb.apps.pyhie.util

object Keys {
    const val EMAIL = "email"
    const val INFO = "User Info"
    const val MAIN_HABITS = "Main Habits"
    const val SLEEP_DATA = "Sleeping Data"
    const val USER_POINTS = "User Points"
    const val SLEEP_INFO = "Sleeping Info"
    const val EATING_DATA = "Eating Data"
    const val EATING_INFO = "Eating Info"
    const val PLANNER_DATA_TODAY = "Planner data for today"
    const val PLANNER_DAT_TOM = "Planner data for tomorrow"
    const val PLANNER_INFO = "Planner info"
    const val SLEEP_SAVED_STATE = "sleeping habit saved"
    const val EAT_SAVED_STATE = "eating habit saved"
    const val CLEANING_SAVED_STATE = "cleaning habit saved"
    const val CLEANING_DATA = "Cleaning data"
    const val CLEANING_INFO = "Cleaning info"
    const val PLANNER_TOM_NOT_SUBMITTED = "Planner for tomorrow is submitted"
    const val SLEEP1_NOT_SUBMITTED = "sleep 1 is submitted"
    const val SLEEP2_NOT_SUBMITTED = "sleep 2 is submitted"
    const val SLEEP3_NOT_SUBMITTED = "sleep 3 is submitted"
    const val EAT1_NOT_SUBMITTED = "eat1 is not submitted"
    const val EAT2_NOT_SUBMITTED = "eat2 is not submitted"
    const val EAT3_NOT_SUBMITTED = "eat3 is not submitted"
    const val EAT4_NOT_SUBMITTED = "eat4 is not submitted"
    const val EAT5_NOT_SUBMITTED = "eat5 is not submitted"
    const val SLEEP_BALANCE = "Sleep balance"
    const val EAT_BALANCE = "Eat balance"
    const val CLEAN_BALANCE = "Clean balance"
    const val PLANNER_BALANCE = "Planner balance"
    const val CURRENT_CHALLENGE = "Current challenge"
    const val CHALLENGE_NOT_SHOWN = "Current challenge not shown"
    const val CLEAN_NOT_SUBMITTED = "Clean is submitted"
    const val PLANNER_NOT_SUBMITTED = "Planner is submitted"
    const val ACTIVATE_CHALLENGE = "Activate challenge"
    const val CHALLENGE_COMPLETED = "Completed challenge"
    const val CHALLENGE_FAILED = "Failed challenge"
    const val CHALLENGE_1_START_DAY = "CHALLENGE_1_START_DAY"
    const val CHALLENGE_3_START_DAY = "CHALLENGE_3_START_DAY"
    const val ADVICE_DAY_NUMBER = "DAY_NUMBER"
    const val ADVICE_NOT_SHOWN = "Advice not shown"
    const val NAME = "NAME"
    const val NEW_LEVEL_NOT_REACHED = "NUMBEROFDAYS"
    const val NOTIFICATIONS_ON = "NOTIFICATIONS_ON"
}